CargoWorld/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Models
{
    public class Group
    {
        [Key]
        public int IdGroup { get; set; }

        public ApplicationUser IdOwner { get; set; }

        [Required]
        [MinLength(3)]
        public string GroupName { get; set; }

        public List<Car> Cars { get; set; }
    }
}

CargoWorld/ViewModels/GroupViewModel.cs
using CargoWorld.Data;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.ViewModels
{
    public class GroupViewModel
    {
        public int IdGroup { get; set; }

        public ApplicationUser IdOwner { get; set; }

        [Required(ErrorMessage = "Назва має бути не пустою")]
        [MinLength(3)]
        public string GroupName { get; set; }

        public IEnumerable<Car> Cars { get; set; }
        
    }
       
}

CargoWorld/Controllers/Api/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CargoWorld.Data;
using CargoWorld.Models;

namespace CargoWorld.Controllers.Api
{
    [Route("api/[controller]")]
    [ApiController]
    public class GroupsController : ControllerBase
    {
        private readonly AppDbContext _context;

        public GroupsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: api/Groups
        [HttpGet]
        public List<Group> GetGroups(string email)
        {
            return  _context.Groups.Where(o=>o.IdOwner.Email == email).AsNoTracking().ToList();
        }

        // GET: api/Groups/5
        [HttpGet("{id}")]
        public async Task<ActionResult<Group>> GetGroup(int id)
        {
            var @group = await _context.Groups.FindAsync(id);

            if (@group == null)
            {
                return NotFound();
            }

            return @group;
        }

        // PUT: api/Groups/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        [HttpPut("{id}")]
        public async Task<IActionResult> PutGroup(int id, Group @group)
        {
            if (id != @group.IdGroup)
            {
                return BadRequest();
            }

            _context.Entry(@group).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GroupExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return NoContent();
        }

        // POST: api/Groups
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        [HttpPost]
        public async Task<ActionResult<Group>> PostGroup(Group @group)
        {
            _context.Groups.Add(@group);
            await _context.SaveChangesAsync();

            return CreatedAtAction("GetGroup", new { id = @group.IdGroup }, @group);
        }

        // DELETE: api/Groups/5
        [HttpDelete("{id}")]
        public async Task<ActionResult<Group>> DeleteGroup(int id)
        {
            var @group = await _context.Groups.FindAsync(id);
            if (@group == null)
            {
                return NotFound();
            }

            _context.Groups.Remove(@group);
            await _context.SaveChangesAsync();

            return @group;
        }

        private bool GroupExists(int id)
        {
            return _context.Groups.Any(e => e.IdGroup == id);
        }
    }
}

CargoWorld/Controllers/CarController.cs
using CargoWorld.Data;
using CargoWorld.Data.FileManager;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private CarRepository _carRepository;
        private UserManager<ApplicationUser> _userManager;
        private IFileManager _fileManager;

        public CarController(IRepository<Car> carRepository, 
            UserManager<ApplicationUser> userManager,
            IFileManager fileManager)
        {
            _carRepository = (CarRepository)carRepository;
            _userManager = userManager;
            _fileManager = fileManager;
        }

        [HttpGet]
        public async Task<IActionResult> CreateCarAsync(int? id)
        {
            if (id == null)
                return View(new CarViewModel());
            else
            {
                var car = _carRepository.Get((int)id);
                return View(new CarViewModel
                {
                    IdOwner = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)),
                    IdCar = (int)car.IdCar,
                    IdDriver = car.IdDriver,
                    IdGroup = null,
                    CarModel = car.CarModel,
                    CarcassNumber = car.CarcassNumber,
                    RegistrationNumber = car.RegistrationNumber,
                    Photo = car.Photo,
                    Color = car.Color,
                    CargoType = car.CargoType,
                    CarType = car.CarType,
                    CarryingCapacity = car.CarryingCapacity,
                    CarryingCapacitySqM = car.CarryingCapacitySqM,
                    HeightCargoCompartment = car.HeightCargoCompartment,
                    WidthCargoCompartment = car.WidthCargoCompartment,
                    LengthCargoCompartment = car.LengthCargoCompartment,
                    CostPerKm = car.CostPerKm
                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateCar(CarViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                return View(cvm);
            }
            var car = new Car
            {
                IdOwner = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)),
                IdCar = cvm.IdCar,
                IdDriver = String.Empty,
                IdGroup = cvm.IdGroup,
                CarModel = cvm.CarModel,
                CarcassNumber = cvm.CarcassNumber,
                RegistrationNumber = cvm.RegistrationNumber,
                Photo = await _fileManager.SaveImage(cvm.Image),
                Color = cvm.Color,
                CargoType = cvm.CargoType,
                CarType = cvm.CarType,
                CarryingCapacity = cvm.CarryingCapacity,
                CarryingCapacitySqM = cvm.CarryingCapacitySqM,
                HeightCargoCompartment = cvm.HeightCargoCompartment,
                WidthCargoCompartment = cvm.WidthCargoCompartment,
                LengthCargoCompartment = cvm.LengthCargoCompartment,
                CostPerKm = cvm.CostPerKm
            };


            if (cvm.IdCar > 0)
                _carRepository.Update(car);
            else
                _carRepository.Create(car);

            if (await _carRepository.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(car);
        }


        public IActionResult ACar(int id)
        {
            return View(_carRepository.Get(id));
        }


        [HttpGet]
        public IActionResult ImDriving()
        {
            var res = _carRepository.IAmDriving(_userManager.GetUserId(HttpContext.User));
            return View(res);
        }

        public async Task<IActionResult> DrivingRefuseAsync(int idCar)
        {
            await _carRepository.RefuseDrivingAsync(idCar);
            // refusing
            return RedirectToAction("ImDriving");
        }


        [HttpGet]
        public IActionResult MyCars(int pageNumber)
        {
            if (pageNumber < 1)
                return RedirectToAction("MyCars", new { pageNumber = 1 });

            var list = _carRepository.GetAll(_userManager.GetUserId(HttpContext.User), pageNumber);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _carRepository.Remove(id);
            await _carRepository.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet("/Image/{image}")]
        public IActionResult Image(string image)
        {
            var type = image.Substring(image.LastIndexOf('.')+1);
            return new FileStreamResult(_fileManager.ImageStream(image), $"image/{type}");
        }
    }
}

CargoWorld/Controllers/RequestController.cs
using CargoWorld.Data;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    [Authorize]
    public class RequestController : Controller
    {
        private RequestRepository _requestManager;
        private UserManager<ApplicationUser> _userManager;
        private UserRepository _userRepository;
        private GroupRepository _groupRepository;
        private IRepository<Car> _carRepository;
        private IRepository<Cargo> _cargoRepository;

        public RequestController(IRepository<Request> requestManager,
            UserManager<ApplicationUser> userManager,
            IRepository<ApplicationUser> userRepository,
            IRepository<Group> groupRepository,
            IRepository<Car> carRepository,
            IRepository<Cargo> cargoRepository)
        {
            _requestManager = (RequestRepository)requestManager;
            _userManager = userManager;
            _userRepository = (UserRepository)userRepository;
            _groupRepository = (GroupRepository)groupRepository;
            _carRepository = carRepository;
            _cargoRepository = cargoRepository;
        }


        #region Company to user
        [HttpGet]
        public IActionResult CompanyToUser()
        {
            var requests = _requestManager.SelectRequests(RequestType.CompanyOffersToUser, _userManager.GetUserId(HttpContext.User));
            return View(requests);
        }

        //Пользователь предлагает компании перевозку груза
        public async Task<IActionResult> AcceptCompanyToUserAsync(int requestId)
        {
            var request = _requestManager.Get(requestId);

            await _requestManager.AcceptCompanyToUserAsync((int)request.IdCargo, (int)request.IdGroup, _userManager.GetUserId(HttpContext.User));

            return RedirectToAction("CompanyToUser");
        }

        [HttpPost]
        public async Task<IActionResult> CreateCompanyToUserAsync(CargoViewModel cvm)
        {
            
            Models.Request request = new Request()
            {
                Recip = _userRepository.Get(cvm.Id_Owner.Id),
                RequestType = RequestType.CompanyOffersToUser,
                Name = "Вам предложили перевозку груза",
                Description = "Вам предложили перевозку груза",
                IdGroup = cvm.idGroup,
                IdCargo = cvm.Id_Cargo
            };
            _requestManager.Create(request);
            await _requestManager.SaveChangesAsync();
            return RedirectToAction("Index","Home");
        }

        #endregion

        #region Driving

        [HttpGet]
        public IActionResult DrivingRequest()
        {
            var requests = _requestManager.SelectRequests(RequestType.DrivingRequest, _userManager.GetUserId(HttpContext.User));
            return View(requests);
        }

        public async Task<IActionResult> AcceptDrivingAsync(int requestId)
        {
            // присвоить id водителя машины, ид пользователя, а все входящие запросы на вождение для этого пользователя удалить

            var request = _requestManager.Get(requestId);

            await _requestManager.AcceptDrivingAsync((int)request.IdCar, _userManager.GetUserId(HttpContext.User));
            return RedirectToAction("DrivingRequest");
        }

        [HttpPost]
        public async Task<IActionResult> CreateDrivingRequestAsync(UserViewModel uvm)
        {
            Models.Request request = new Request()
            {
                IdCar = uvm.IdCarWithoutDriver,
                Recip = _userRepository.Get(uvm.ApplicationUser.Id),
                RequestType = RequestType.DrivingRequest,
                Name = "Вас запрошують працювати водієм",
                Description = "Вас запрошують працювати водієм"

            };
            _requestManager.Create(request);
            await _requestManager.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region User to company

        public async Task<IActionResult> CreateUserToCompanyAsync(UserViewModel uvm)
        {
            Models.Request request = new Request()
            {
                Recip = _userRepository.Get(uvm.ApplicationUser.Id),
                IdCargo = uvm.IdCargo,
                RequestType = RequestType.UserOffersToCompany,
                Name = "Вам пропонують перевезти вантаж",
                Description = "Вам пропонують перевезти вантаж"
            };
            _requestManager.Create(request);
            await _requestManager.SaveChangesAsync();
            return RedirectToAction("DrivingRequest");

        }


        [HttpGet]
        public IActionResult UserToCompany()
        {
            //здеся проверять на всю 
            var requests = _requestManager.SelectRequests(RequestType.UserOffersToCompany, _userManager.GetUserId(HttpContext.User));

            List<RequestViewModel> list = new List<RequestViewModel>();

            foreach (Request r in requests)
            {
                list.Add(new RequestViewModel
                {
                    Request = r,
                    Groups = _groupRepository.GetAll(_userManager.GetUserId(HttpContext.User))
                    .Where(o => o.Cars.FirstOrDefault(o => o.CargoType == _cargoRepository.Get((int)r.IdCargo).CargoType) != null)
                });
            }

            UserToCompanyViewModel utc = new UserToCompanyViewModel
            {
                Requests = list
            };


            return View(utc);
        }

        [HttpPost]
        public async Task<IActionResult> AcceptUserToCompanyAsync(UserToCompanyViewModel req)
        {
            // есть два варика, сформировать групу под груз, или выбрать из списка групу из существующих куда пихать(груз добавляется в cargoin the car)


            var request = _requestManager.Get((int)req.IdRequest);
            await _requestManager.AcceptUserToCompany((int)request.IdCargo, (int)req.IdGroup, request.Id);
            return RedirectToAction("CompanyToUser");
        }




        #endregion

        public async Task<IActionResult> DeclineRequestAsync(int id, string sender)
        {
            _requestManager.Remove(id);
            await _requestManager.SaveChangesAsync();
            return RedirectToAction(sender);
        }
    }
}

CargoWorld/Views/Groups/AGroup.cshtml
@model GroupViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = Model.GroupName;
}


<div>

    <h3> @Localizer["groupName"] - @Model.GroupName </h3>
    <hr />

    @if (ViewBag.FreeCarsCount > 0)
    {
        <span>@Localizer["ableCars"]:</span>
        <table class="table table-hover table-responsive">
            <thead>
                <tr>

                    <th class="text-center">@Localizer["photo"]</th>
                    <th class="text-center">@Localizer["car"]</th>
                    <th class="text-center">@Localizer["regNumber"]</th>
                    <th class="text-center"> </th>
                </tr>
            </thead>
            <tbody>


                @foreach (var freecar in ViewBag.FreeCars)
                {
                    <tr>
                        <td class="text-center">
                            @if (!String.IsNullOrEmpty(@freecar.Photo))
                            {
                                var imagePath = $"/content/webs/{@freecar.Photo}";
                                <img src="@imagePath" height="50" width="50" />
                            }
                        </td>
                        <td class="text-center">
                            @freecar.CarModel
                        </td>
                        <td>
                            @freecar.RegistrationNumber
                        </td>
                        <td>
                            <a class="btn btn-success" asp-controller="Groups" asp-action="AddCarToGroup" asp-route-idCar="@freecar.IdCar" asp-route-idGroup="@Model.IdGroup">@Localizer["addToGroup"]</a>
                        </td>
                    </tr>

                }

            </tbody>
        </table>
    }
    else
    {
        <label>@Localizer["anyFreeCars"]</label>
    }

    <hr />

    @if (Model?.Cars.Count() > 0)
    {
        <p>
            <a class="btn btn-success" asp-controller="Groups" asp-action="GetOptimalCargoForGroup" asp-route-idGroup="@Model.IdGroup">@Localizer["optiCagros"]</a>
        </p>
    }


    @if (Model.Cars.Count() == 0)
    {
        <label>@Localizer["none"]</label>
    }
    else
    {
        <span>@Localizer["carList"]:</span>
        <table class="table table-hover table-responsive">
            <thead>
                <tr>
                    <th class="text-center">
                        Photo
                    </th>
                    <th class="text-center">
                        @Localizer["carName"]
                    </th>
                    <th class="text-center">
                        @Localizer["cargoNumb"]
                    </th>
                    <th class="text-center">
                        @Localizer["editGroup"]
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cr in Model.Cars)
                {
                    <tr>
                        <td class="text-center">
                            @if (!String.IsNullOrEmpty(cr.Photo))
                            {
                                var imagePath = $"/content/webs/{cr.Photo}";
                                <img src="@imagePath" height="50" width="50" />
                            }
                        </td>
                        <td class="text-center">
                            <a asp-controller="Car" asp-action="ACar" asp-route-id="@cr.IdCar">  @cr.CarModel </a>
                        </td>
                        <td class="text-center">
                            @cr.RegistrationNumber
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger" asp-controller="Groups" asp-action="DeleteCarFromGroup" asp-route-idCar="@cr.IdCar" asp-route-idGroup="@cr.IdGroup.IdGroup"> @Localizer["deleteCar"]</a>
                        </td>
                    </tr>
                }

            </tbody>
        </table>
    }
    <a class="btn btn-danger" asp-controller="Groups" asp-action="DeleteGroup" asp-route-id="@Model.IdGroup">@Localizer["deleteGroup"]</a>
</div>

CargoWorld/Views/Groups/CreateGroup.cshtml
@model GroupViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = Localizer["new"];
}

<div class="text-center">
    <form asp-controller="Groups" asp-action="CreateGroup" method="post">
        <div>
            <label>
                @Localizer["groupName"]
            </label>
            <input asp-for="GroupName" />

            @if (Model.IdGroup != 0)
            {

                <h3>@Localizer["addCars"]</h3>

                <ul>
                    @foreach (var cr in Model.Cars)
                    {
                        <li>
                            @cr.CarModel
                        </li>
                    }
                </ul>
            }
        </div>

        <input class="btn btn-success" type="submit" value="@Localizer["create"]" />
    </form>
</div>

CargoWorld/Views/Groups/GetOptimalCargoForGroup.cshtml
@model OptimalCargoViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


<p>
    <label>@Localizer["groupName"] - @Model.OurGroup.GroupName</label>
</p>

@if (Model.Cargos.Count() == 0)
{
    <label>@Localizer["none"]</label>
}
else
{
    <table class="table table-hover table-responsive">
        <thead>
            <tr>
                <th class="text-center">
                    
                </th>
                <th class="text-center">
                    @Localizer["name"]
                </th>
                <th class="text-center">
                    @Localizer["cargoType"]
                </th>
                <th class="text-center">
                    @Localizer["dep"]
                </th>
                <th class="text-center">
                    @Localizer["dest"]
                </th>
                <th class="text-center">
                    @Localizer["weight"]
                </th>
                <th class="text-center">
                    @Localizer["bulk"]
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Cargo cr in Model.Cargos)
            {
                <tr>
                    <td class="text-center">
                        @if (!String.IsNullOrEmpty(cr.Photo))
                        {
                            var imagePath = $"/content/webs/{cr.Photo}";
                            <img src="@imagePath" height="100" width="100" />
                        }
                    </td>
                    <td class="text-center">
                        @cr.CargoName
                    </td>
                    <td class="text-center">
                        @cr.CargoType
                    </td>
                    <td class="text-center">
                        @cr.DeparturePoint
                    </td>
                    <td class="text-center">
                        @cr.DestinationPoint
                    </td>
                    <td class="text-center">
                        @cr.Weight
                    </td>
                    <td class="text-center">
                        @cr.Bulk
                        <br />
                        ____
                        <h1>
                            @cr.Id_Owner.Id
                        </h1>
                        ____
                    </td>
                    <td class="text-center">
                        <form asp-controller="Request" asp-action="CreateCompanyToUser" method="post" enctype="multipart/form-data">
                            <input asp-for="cvm.Id_Cargo" value="@cr.Id_Cargo" type="hidden" />
                            <input asp-for="cvm.Id_Owner.Id" value="@cr.Id_Owner.Id" type="hidden" />
                            <input asp-for="cvm.idGroup" value="@Model.OurGroup.IdGroup" type="hidden" />

                            <input class="btn btn-success" type="submit" value="@Localizer["ofer"]" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

}

CargoWorld/Views/Groups/GroupList.cshtml
@model ListViewModel<Group>

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewBag.Title = Localizer["title"];
}

@if (Enumerable.Count(Model.List) == 0)
{
    <h3 class="text-center">@Localizer["none"]</h3>
    <a asp-controller="Groups" asp-action="CreateGroup">@Localizer["create"]</a>
}
else
{
    <table class="table table-hover table-responsive ml-5">
        <thead>
            <tr>
                <th class="text-center">
                    @Localizer["one"]
                </th>
                <th class="text-center">
                    @Localizer["carsCount"]
                </th>

            </tr>
        </thead>
        <tbody >
            @foreach (var cr in Model.List)
            {
                <tr>
                    <td class="text-center">
                        <a asp-controller="Groups" asp-action="AGroup" asp-route-idOfGroup="@cr.IdGroup">
                            @cr.GroupName
                        </a>
                    </td>
                    <td class="text-center">
                        @cr.Cars?.Count()
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div>
        @if (Model.PageNumber > 1)
        {
            <a class="btn btn-success" asp-controller="Groups" asp-action="GroupList" asp-route-pageNumber="@(Model.PageNumber-1)">@Localizer["prev"]</a>

        }
        @if (Model.CanNext)
        {

            <a class="btn btn-success" asp-controller="Groups" asp-action="GroupList" asp-route-pageNumber="@(Model.PageNumber + 1)">@Localizer["next"]</a>
        }
    </div>
}