CargoWorld/Models/Cargo.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Models
{
    public class Cargo
    {
        [Key]
        public int Id_Cargo { get; set; }
        public ApplicationUser Id_Owner { get; set; }
        public ICollection<CargoInCar> Transfer { get; set; }
        public bool IsDelivered { get; set; } = false;

        [Required]
        [MinLength(2)]
        public string CargoName { get; set; }
        /// <summary>
        /// Точка отправки
        /// </summary>
        [Required]
        [MinLength(2)]
        public string DeparturePoint { get; set; }
        /// <summary>
        /// Точка доставки
        /// </summary>
        [Required]
        [MinLength(2)]
        public string DestinationPoint { get; set; }
        [Required]
        public string Photo { get; set; }
        /// <summary>
        /// Вес в кг
        /// </summary>
        [Required]
        [Range(0d,50000d)]
        public int Weight { get; set; }
        /// <summary>
        /// Какой груз? Жидкий\сыпучий\доски\бетонные блоки 
        /// </summary>
        public string CargoType { get; set; }

        [Required]
        [Range(0d, 500d)]
        public double Height { get; set; }
        [Required]
        [Range(0d, 50000d)]
        public double Width { get; set; }
        [Required]
        [Range(0d, 50000d)]
        public double Length { get; set; }
        /// <summary>
        /// Может ли груз быть разделён на несколько частей?
        /// </summary>
        public bool CanBeSepateted {get;set;}
        /// <summary>
        /// Объём
        /// </summary>
       
        public double Bulk { get; set; }

    }
}

CargoWorld/ViewModels/CargoViewModel.cs
using CargoWorld.Models;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.ViewModels
{
    public class CargoViewModel
    {
        public int Id_Cargo { get; set; }
        public ApplicationUser Id_Owner { get; set; }
        public CargoInCar Transfer { get; set; }
        public bool IsDelivered { get; set; }

        [Required(ErrorMessage = "Має бути заповнений")]
        [MinLength(2)]
        public string CargoName { get; set; }
        /// <summary>
        /// Точка отправки
        /// </summary>
        [Required(ErrorMessage = "Має бути заповнений")]

        [MinLength(2)]
        public string DeparturePoint { get; set; }
        /// <summary>
        /// Точка доставки
        /// </summary>
        [Required(ErrorMessage = "Має бути заповнений")]
        [MinLength(2)]
        public string DestinationPoint { get; set; }
        public string Photo { get; set; }
        /// <summary>
        /// Вес в кг
        /// </summary>
        [Required]
        [Range(0d, 50000d)]
        public int Weight { get; set; }
        /// <summary>
        /// Какой груз? Жидкий\сыпучий\доски\бетонные блоки 
        /// </summary>
        public string CargoType { get; set; }

        [Required]
        [Range(0.1d, 500d, ErrorMessage = "> 0.1")]
        public double Height { get; set; }
        [Required]
        [Range(0.1d, 500d, ErrorMessage = "> 0.1")]
        public double Width { get; set; }
        [Required]
        [Range(0.1d, 500d,ErrorMessage = "> 0.1")]
        public double Length { get; set; }
        /// <summary>
        /// Может ли груз быть разделён на несколько частей?
        /// </summary>
        public bool CanBeSepateted { get; set; }
        /// <summary>
        /// Объём
        /// </summary>


        [Range(0.1d, 500000d, ErrorMessage = "> 0.1")]
        public double Bulk { get; set; }


        public IFormFile Image { get; set; } = null;

        public int? idGroup { get; set; }
    }
}

CargoWorld/ViewModels/OptimalGroupViewModel.cs
using CargoWorld.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.ViewModels
{
    public class OptimalGroupViewModel
    {
        public IEnumerable<Car> CarsThisGroup { get; set; }

        public Cargo Cargo { get; set; }
    }
}

CargoWorld/Controllers/CargoController.cs
using CargoWorld.Data;
using CargoWorld.Data.FileManager;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    [Authorize]
    public class CargoController : Controller
    {
        private CargoRepository _cargoRepository;
        private UserManager<ApplicationUser> _userManager;
        private IFileManager _fileManager;
        private GroupRepository _groupRepository;

        public CargoController(IRepository<Cargo> cargoRepository,
            UserManager<ApplicationUser> userManager,
            IRepository<Group> groupRepository,
            IFileManager fileManager)
        {
            _cargoRepository = (CargoRepository)cargoRepository;
            _userManager = userManager;
            _fileManager = fileManager;
            _groupRepository = (GroupRepository)groupRepository;
        }

        [HttpGet]
        public IActionResult ACargo(int id)
        {
            var cargo = _cargoRepository.Get(id);
            CargoViewModel cvm = new CargoViewModel
            {
                Id_Cargo = cargo.Id_Cargo,
                Id_Owner = cargo.Id_Owner,
                IsDelivered = cargo.IsDelivered,
                CargoName = cargo.CargoName,
                DeparturePoint = cargo.DeparturePoint,
                DestinationPoint = cargo.DestinationPoint,
                Photo = cargo.Photo,
                Weight = cargo.Weight,
                CargoType = cargo.CargoType,
                Height = cargo.Height,
                Width = cargo.Width,
                Length = cargo.Length,
                CanBeSepateted = cargo.CanBeSepateted,
                Bulk = cargo.Bulk

            };
            var grps = _groupRepository.GetAll(_userManager.GetUserId(HttpContext.User))
                .Where(o=>o.Cars.FirstOrDefault(o=>o.CargoType == cvm.CargoType) != null);
            ViewBag.GroupsToOffer = grps;
            ViewBag.CurUserId = _userManager.GetUserId(HttpContext.User);
            return View(cvm);
        }

        [HttpGet]
        public IActionResult CreateCargo(int? id)
        {
            if (id == null)
                return View(new CargoViewModel());
            else
            {
                var cargo = _cargoRepository.Get((int)id);
                return View(new CargoViewModel
                {
                    Id_Cargo = cargo.Id_Cargo,
                    Id_Owner = cargo.Id_Owner,
                    IsDelivered = cargo.IsDelivered,
                    CargoName = cargo.CargoName,
                    DeparturePoint = cargo.DeparturePoint,
                    DestinationPoint = cargo.DestinationPoint,
                    Photo = cargo.Photo,
                    Weight = cargo.Weight,
                    CargoType = cargo.CargoType,
                    Height = cargo.Height,
                    Width = cargo.Width,
                    Length = cargo.Length,
                    CanBeSepateted = cargo.CanBeSepateted,
                    Bulk = cargo.Bulk

                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateCargo(CargoViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                return View(cvm);
            }
            var user = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User));
            var cargo = new Cargo
            {
                Id_Cargo = cvm.Id_Cargo,
                Id_Owner = user,
                IsDelivered = cvm.IsDelivered,
                CargoName = cvm.CargoName,
                DeparturePoint = cvm.DeparturePoint,
                DestinationPoint = cvm.DestinationPoint,
                Photo = await _fileManager.SaveImage(cvm.Image),
                Weight = cvm.Weight,
                CargoType = cvm.CargoType,
                Height = cvm.Height,
                Width = cvm.Width,
                Length = cvm.Length,
                CanBeSepateted = cvm.CanBeSepateted,
                Bulk = cvm.Bulk


            };

            if (cvm.Id_Cargo > 0)
                _cargoRepository.Update(cargo);
            else
                _cargoRepository.Create(cargo);

            if (await _cargoRepository.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(cvm);

        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id, int? pageNumber)
        {
            _cargoRepository.Remove(id);
            await _cargoRepository.SaveChangesAsync();
            if(Convert.ToInt32(pageNumber) == 0) 
                return RedirectToAction("Index", "Home");
            else
                return RedirectToAction("AdminPanel", "Home", new { pageNumber });
        }

       

        public IActionResult CargoList(int pageNumber)
        {
            if (pageNumber < 1)
                return RedirectToAction("CargoList", new { pageNumber = 1 });

            var list = _cargoRepository.GetAll(_userManager.GetUserId(HttpContext.User), pageNumber);
            return View(list);
        }

        [HttpGet("/Image/{image}")]
        public IActionResult Image(string image)
        {
            var type = image.Substring(image.LastIndexOf('.') + 1);
            return new FileStreamResult(_fileManager.ImageStream(image), $"image/{type}");
        }


        [HttpGet]
        public IActionResult IMTransporting()
        {
            var cargos = _cargoRepository.CargosImTransporting(_userManager.GetUserId(HttpContext.User));
            return View(cargos);
        }

        public async Task<IActionResult> DeleteTransportedAsync(int id)
        {
            var cic = await _cargoRepository.DeleteTransportingAsync(id);
            cic.Transporter = null;
            await _cargoRepository.UpdateAsync(cic);
            return RedirectToAction("IMTransporting");
        }


       [Obsolete("Не сделано")]
        public async Task<IActionResult> SetDeliveredAsync(int idCargo)
        {
            Cargo cr = _cargoRepository.Get(idCargo);
            cr.IsDelivered = true;
            _cargoRepository.Update(cr);
            await _cargoRepository.SaveChangesAsync();
            return RedirectToAction("IMTransporting");
        }

        public IActionResult OptimalGroup(int idCargo)
        {

            var ogv = new OptimalGroupViewModel
            {
                CarsThisGroup = _groupRepository.CreateGroupForCargo(idCargo, _userManager.GetUserId(HttpContext.User)),
                Cargo = _cargoRepository.Get(idCargo)
            };
            return View(ogv);
        }
    }
}

CargoWorld/Controllers/GroupsController.cs
using CargoWorld.Data;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private GroupRepository _groupsRepository;
        private UserManager<ApplicationUser> _userManager;
        private CarRepository _carManager;
        private CargoRepository _cargoManager;
        private UserRepository _userRepository;

        public GroupsController(IRepository<Group> groupsRepository,
            UserManager<ApplicationUser> userManager,
            IRepository<Car> carManager,
            IRepository<Cargo> cargoManager,
            IRepository<ApplicationUser> userRepository)
        {
            _groupsRepository = (GroupRepository)groupsRepository;
            _userManager = userManager;
            _carManager = (CarRepository)carManager;
            _cargoManager = (CargoRepository)cargoManager;
            _userRepository = (UserRepository)userRepository;
        }

        public IActionResult AGroup(string idOfGroup)
        {
            var group = _groupsRepository.Get(Convert.ToInt32(idOfGroup));

            var freeCars = _groupsRepository.GetCarsWithoutGroup(_userManager.GetUserId(HttpContext.User));
            ViewBag.FreeCars = freeCars;
            ViewBag.FreeCarsCount = freeCars.Count();
            GroupViewModel gvm = new GroupViewModel
            {
                IdGroup = (int)group.IdGroup,
                IdOwner = group.IdOwner,
                GroupName = group.GroupName,
                Cars = _carManager.CarsInRep((int)group.IdGroup)
            };
            return View(gvm);
        }


        [HttpGet]
        public IActionResult GroupList(int pageNumber)
        {
            if (pageNumber < 1)
                return RedirectToAction("GroupList", new { pageNumber = 1 });

            var list = _groupsRepository.GetAll(_userManager.GetUserId(HttpContext.User), pageNumber);
            return View(list);
        }


        [HttpGet]
        public IActionResult CreateGroup(int? id)
        {
           
            if (id == null)
                return View(new GroupViewModel
                {
                    Cars = _groupsRepository.GetCarsWithoutGroup(id.ToString())
                });
            else
            {
                var group = _groupsRepository.Get((int)id);
                var cars = _groupsRepository.GetCarsWithoutGroup(_userManager.GetUserId(HttpContext.User));
                return View(new GroupViewModel
                {
                    IdGroup = (int)group.IdGroup,
                    IdOwner = group.IdOwner,
                    GroupName = group.GroupName,
                    Cars = cars,

                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateGroupAsync(GroupViewModel gvm)
        {
            if (!ModelState.IsValid)
            {
                return View(gvm);
            }
            var group = new Group
            {
                IdGroup = gvm.IdGroup,
                GroupName = gvm.GroupName,
                IdOwner = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User))
            };



            if (gvm.IdGroup > 0)
                _groupsRepository.Update(group);
            else
                _groupsRepository.Create(group);

            if (await _groupsRepository.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(group);
        }


        [HttpGet]
        public async Task<IActionResult> DeleteGroup(int id)
        {
            _groupsRepository.Remove(id);
            await _groupsRepository.SaveChangesAsync();
            return RedirectToAction("GroupList");
        }

        [HttpGet]
        [Obsolete("Работает, но низя изменять уже занятую запись")]
        public async Task<IActionResult> AddCarToGroupAsync(int idCar, int idGroup)
        {
            var cvm = _carManager.Get(idCar);
            var group = _groupsRepository.Get(idGroup);
            cvm.IdGroup = group;
           
            _carManager.Update(cvm);
            await _carManager.SaveChangesAsync();

            return RedirectToAction("AGroup", new { idOfGroup = idGroup });
        }

        public async Task<IActionResult> DeleteCarFromGroupAsync(int idCar, int idGroup)
        {
            var cvm = _carManager.GetTracking(idCar);
            cvm.IdGroup = null;
            

            _carManager.Update(cvm);
            await _carManager.SaveChangesAsync();
            return RedirectToAction("AGroup", new { idOfGroup = idGroup });
        }


        public IActionResult GetOptimalCargoForGroup(int idGroup)
        {
            var cvm = new OptimalCargoViewModel
            {
                Cargos = _cargoManager.SearchOptimalCargoForGroup(idGroup),
                OurGroup = _groupsRepository.Get(idGroup)
            };
            return View(cvm);
        }

        [HttpPost]
        public async Task<IActionResult> CreateOptimalGroupAsync(OptimalGroupViewModel ogvm, int[] items)
        {

            List<Car> carsThisGroup = new List<Car>();

            foreach(int i in items)
            {
                carsThisGroup.Add(_carManager.Get(i));
            }
           

            Group group = new Group()
            {
                IdGroup = 0,
                IdOwner = _userRepository.Get(_userManager.GetUserId(HttpContext.User)),
                GroupName = "GroupFor" + _cargoManager.Get(ogvm.Cargo.Id_Cargo).CargoName,
            };

            _groupsRepository.Create(group);
            
           // await _groupsRepository.SaveChangesAsync();

            foreach(Car car in carsThisGroup)
            {
                car.IdGroup = group;
               
            }

            _groupsRepository.UpdateMany(carsThisGroup); // ошбика отслеживания Пользователя?!
            await _groupsRepository.SaveChangesAsync();

            return RedirectToAction("Index","Home");
        }
    } 
}

CargoWorld/Views/Cargo/ACargo.cshtml
@model CargoViewModel

@{
    ViewBag.Title = Model.CargoName;
}

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


@if (!String.IsNullOrEmpty(Model.Photo))
{
    var imagePath = $"/content/webs/{Model.Photo}";
    <img src="@imagePath" height="200" width="200" />
}

<h3>@Localizer["name"] - @Model.CargoName </h3>

<h3>@Localizer["cargoType"] - @Model.CargoType </h3>

<h3>@Localizer["dep"] - @Model.DeparturePoint </h3>

<h3>@Localizer["dest"] - @Model.DestinationPoint </h3>

<h3>@Localizer["bulk"] - @Model.Bulk </h3>




@if (Model.Id_Owner.Id != ViewBag.CurUserId)
{
    @if (Enumerable.Count(ViewBag.GroupsToOffer) > 0)
    {
        <form asp-controller="Request" asp-action="CreateCompanyToUser" method="post" enctype="multipart/form-data">
            <input asp-for="Id_Cargo" type="hidden" />
            <input asp-for="Id_Owner.Id" type="hidden" />
            <select asp-for="idGroup">
                @foreach (var cr in ViewBag.GroupsToOffer)
                {
                    <option value="@cr.IdGroup">@cr.GroupName</option>
                }
            </select>
            <input class="btn btn-success" type="submit" value="@Localizer["sendReq"]" />
        </form>
    }
}

CargoWorld/Views/Cargo/CargoList.cshtml
@model ListViewModel<Cargo>

@{
    ViewBag.Title = Localizer["title"];
}

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer



@if (Enumerable.Count(Model.List) == 0)
{
    <h3>@Localizer["empty"]</h3>
    <a asp-controller="Cargo" asp-action="CreateCargo">@Localizer["create"]</a>
}
else
{
    <table class="table table-hover table-responsive ml-5 ">
        <thead>
            <tr>
                <th class="text-center">@Localizer["photo"]</th>
                <th class="text-center">@Localizer["cargoName"]</th>
                <th class="text-center"></th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var c in Model.List)
            {
                <tr>
                    <td class="text-center">
                        @if (!String.IsNullOrEmpty(c.Photo))
                        {
                            var imagePath = $"/content/webs/{c.Photo}";
                            <img src="@imagePath" height="50" width="50" />
                        }
                    </td>
                    <td class="text-center">
                        <a asp-controller="Cargo" asp-action="ACargo" asp-route-id="@c.Id_Cargo">@c.CargoName</a>
                    </td>

                    <td class="text-center">
                        <a class="btn btn-success" asp-controller="Cargo" asp-action="CreateCargo" asp-route-id="@c.Id_Cargo"> @Localizer["edit"]</a>

                        <a class="btn btn-success" asp-controller="Cargo" asp-action="Remove" asp-route-id="@c.Id_Cargo"> @Localizer["remove"]</a>
                    </td>

                </tr>
            }

        </tbody>
    </table>


    <div>
        @if (Model.PageNumber > 1)
        {
            <a class="btn btn-success" asp-controller="Cargo" asp-action="CargoList" asp-route-pageNumber="@(Model.PageNumber-1)">@Localizer["prev"]</a>

        }
        @if (Model.CanNext)
        {
            <a class="btn btn-success" asp-controller="Cargo" asp-action="CargoList" asp-route-pageNumber="@(Model.PageNumber+1)">@Localizer["next"]</a>

        }
    </div>
}

CargoWorld/Views/Cargo/CreateCargo.cshtml
@model CargoViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
        ViewBag.Title = Localizer["title"];
}



<form asp-controller="Cargo" asp-action="CreateCargo" method="post" enctype="multipart/form-data">
    <table align="center">
        <tr>
            <td>
                <input asp-for="Id_Cargo" type="hidden" />
            </td>

        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["name"] -
                </label>
            </td>
            <td>
                <input asp-for="CargoName" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["dep"] -
                </label>
            </td>
            <td>
                <input asp-for="DeparturePoint" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["dest"] -
                </label>
            </td>
            <td>
                <input asp-for="DestinationPoint" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["weight"] (kg) -
                </label>
            </td>
            <td>
                <input asp-for="Weight" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["cargoType"] -
                </label>
            </td>
            <td>
                <select asp-for="CargoType">
                    <option value="box">@Localizer["box"]</option>
                    <option value="solid">@Localizer["solid"]</option>
                    <option value="liquid">@Localizer["liquid"]</option>
                    <option value="loose">@Localizer["loose"]</option>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <label>@Localizer["canSep"]</label> @Html.CheckBox("CanBeSepateted", Model.CanBeSepateted)
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["height"]
                </label>
            </td>
            <td>
                <input asp-for="Height" placeholder="@Localizer["notif"]" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["width"]
                </label>
            </td>
            <td>
                <input asp-for="Width" placeholder="@Localizer["notif"]" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["length"]
                </label>
            </td>
            <td>
                <input asp-for="Length" placeholder="@Localizer["notif"]" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["bulk"] -
                </label>
            </td>
            <td>
                <input asp-for="Bulk" />
            </td>
        </tr>
        <tr>
            <td>
                <label class="mb-2 mt-2">
                    @Localizer["picture"] -
                </label>
            </td>
            <td>
                <input asp-for="Image" />
            </td>
        </tr>
        <tr>
            <td>
                <input class="btn btn-success" type="submit" value="@Localizer["add"]" />
            </td>
        </tr>
    </table>
</form>

CargoWorld/Views/Cargo/IMTransporting.cshtml
@model IEnumerable<CargoInCar>


@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


@if (Model == null || Model.Count() == 0)
{
    <div class="text-center">
        <label>@Localizer["empty"]</label>
    </div>
}
else
{

    <table class="table table-hover table-responsive table-striped ml-5">
        <thead>
            <tr>
                <th>@Localizer["photo"]</th>
                <th class="text-center">@Localizer["name"]</th>
                <th class="text-center">@Localizer["depPoint"]</th>
                <th class="text-center">@Localizer["dest"]</th>
                <th class="text-center">@Localizer["cargoType"]</th>
                <th class="text-center">@Localizer["wasDeliv"]</th>
                <th class="text-center"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cr in Model)
            {
                <tr>
                    <td class="text-center">
                        @if (!String.IsNullOrEmpty(cr.Cargo.Photo))
                        {
                            var imagePath = $"/content/webs/{cr.Cargo.Photo}";
                            <img src="@imagePath" height="50" width="50" />
                        }
                    </td>

                    <td class="text-center">

                        <a asp-controller="Cargo" asp-action="ACargo" asp-route-id="@cr.Cargo.Id_Cargo"> @cr.Cargo.CargoName</a> 

                    </td>
                    <td class="text-center">

                        @cr.Cargo.DeparturePoint

                    </td>
                    <td class="text-center">

                        @cr.Cargo.DestinationPoint

                    </td>
                    <td class="text-center">

                        @cr.Cargo.CargoType

                    </td>
                    <td class="text-center">
                        @{
                            if (cr.Cargo.IsDelivered)
                            {
                                @Localizer["deliv"]
                            }
                            else
                            {
                                @Localizer["notDeliv"]
                            }
                        }
                    </td>
                    <td class="text-center">
                        @if (!cr.Cargo.IsDelivered)
                        {
                            <a class="btn btn-success" asp-controller="Cargo" asp-action="SetDelivered" asp-route-idCargo="@cr.Cargo.Id_Cargo">@Localizer["set"]</a>
                        }
                        @if (cr.Cargo.IsDelivered)
                        {
                            <a class="btn btn-success" asp-controller="Cargo" asp-action="DeleteTransported" asp-route-id="@cr.Id_Delivery">@Localizer["deleteFromTransp"]</a>
                        }
                    </td>
                </tr>
            }

        </tbody>
    </table>

}

CargoWorld/Views/Cargo/OptimalGroup.cshtml
@model OptimalGroupViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


<p>@Localizer["offeredGroup"] - <h4>@Model.Cargo.CargoName</h4> </p>



@if (Model.CarsThisGroup.Count() == 0)
{
    <label>@Localizer["none"]</label>
}
else
{
    <table  class="table table-hover table-responsive ">
        <thead>
            <tr>
                <td class="text-center">
                    @Localizer["photo"]
                </td>
                <td class="text-center">
                    @Localizer["model"]
                </td>
                <td class="text-center">
                    @Localizer["carType"]
                </td>
                <td class="text-center">
                    @Localizer["numb"]
                </td>
                <td>
                </td>
            </tr>
        </thead>
        <tbody>
            @foreach (var car in Model.CarsThisGroup)
            {
                <tr>
                    <td class="text-center">
                        @if (!String.IsNullOrEmpty(car.Photo))
                        {
                            var imagePath = $"/content/webs/{car.Photo}";
                            <img src="@imagePath" height="200" width="200" />
                        }
                    </td>
                    <td class="text-center">
                        @car.CarModel
                    </td>
                    <td class="text-center">
                        @car.CarType
                    </td>
                    <td class="text-center">
                        @car.RegistrationNumber
                    </td>
                    <td class="text-center">
                        <form asp-controller="Groups" asp-action="CreateOptimalGroup" method="post" enctype="multipart/form-data">
                            <input asp-for="Cargo.Id_Cargo" value="@Model.Cargo.Id_Cargo" type="hidden" />
                            <input class="btn btn-success" type="submit" value="@Localizer["create"]" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    
}