CargoWorld/Controllers/AuthController.cs
using CargoWorld.Data;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    public class AuthController : Controller
    {
        private UserManager<ApplicationUser> _userManager;
        private SignInManager<ApplicationUser> _signInManager;
        private UserRepository _userRepository;

        public AuthController(SignInManager<ApplicationUser> signInManager,
            UserManager<ApplicationUser> userManager,
            IRepository<ApplicationUser> userRepository)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _userRepository = (UserRepository)userRepository;
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel vm)
        {
            var res = await _signInManager.PasswordSignInAsync(vm.UserName, vm.Password, false, false);
            if (!res.Succeeded)
            {
                return View(vm);
            }
            return RedirectToAction("Index", "Home");

        }


        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }

            var User = new ApplicationUser
            {
                UserName = vm.Email,
                Email = vm.Email,
                Name = vm.Name,
                Surname = vm.Surname,
                Age = vm.Age
            };
            var result = await _userManager.CreateAsync(User, vm.Password);


            if (result.Succeeded)
            {
                Registration(User.Email, User.Name);
                await _signInManager.SignInAsync(User, false);

                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpGet]
        public IActionResult ChangePass()
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassAsync(RegisterViewModel rvm)
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            await ResetAsync(user.Email, rvm.Password);
            await _signInManager.SignOutAsync();
            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Reset()
        {
            return View(new RegisterViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> ResetAsync(RegisterViewModel rvm)
        {
            if (!ModelState.IsValid)
            {
                return View(rvm);
            }
            await ResetAsync(rvm.Email);
            return RedirectToAction("Login");
        }

        public async Task<IActionResult> DeleteAsync(string id, int pageNumber)
        {
            var user =  _userRepository.Get(id);
            if (user != null)
            {
                IdentityResult result = await _userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("AdminPanel", "Home",new { pageNumber});
                }
                return RedirectToAction("AdminPanel", "Home", new { pageNumber });
            }
            return RedirectToAction("Index", "Home");
        }

        private void Registration(string email, string name)
        {
            try
            {
                // отправитель - устанавливаем адрес и отображаемое в письме имя
                MailAddress from = new MailAddress("illia.bezuhlyi@nure.ua", "Cargo world");
                // кому отправляем
                MailAddress to = new MailAddress(email);

                // создаем объект сообщения
                MailMessage m = new MailMessage(from, to);
                // тема письма
                m.Subject = "Welcome";
                // текст письма
                m.Body = name + " welcome in cargo world service";
                // письмо представляет код html
                m.IsBodyHtml = true;
                // адрес smtp-сервера и порт, с которого будем отправлять письмо
                SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);

                // логин и пароль
                smtp.Credentials = new NetworkCredential("illia.bezuhlyi@nure.ua", "TLnK5nd3");
                smtp.EnableSsl = true;
                smtp.Send(m);

            }
            catch (Exception ex)
            {

            }
        }

        private async Task ResetAsync(string email)
        {
            var user = await _userManager.FindByNameAsync(email);
            if (user != null)
            {
                string newPass = "FEgrkogbb" + (new Random()).Next(0, 9999) + "_forgot" + (new Random()).Next(99, 333);
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                try
                {
                    // отправитель - устанавливаем адрес и отображаемое в письме имя
                    MailAddress from = new MailAddress("illia.bezuhlyi@nure.ua", "Cargo world");
                    // кому отправляем
                    MailAddress to = new MailAddress(email);

                    // создаем объект сообщения
                    MailMessage m = new MailMessage(from, to);
                    // тема письма
                    m.Subject = "Password restoring";
                    // текст письма
                    m.Body = "New passport is : " + newPass;
                    // письмо представляет код html
                    m.IsBodyHtml = true;
                    // адрес smtp-сервера и порт, с которого будем отправлять письмо
                    SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);

                    // логин и пароль
                    smtp.Credentials = new NetworkCredential("illia.bezuhlyi@nure.ua", "TLnK5nd3");
                    smtp.EnableSsl = true;
                    smtp.Send(m);

                    var res = await _userManager.ResetPasswordAsync(user, code, newPass);


                }
                catch (Exception ex)
                {

                }
            }
        }
        private async Task ResetAsync(string email, string pass)
        {
            var user = await _userManager.FindByNameAsync(email);
            if (user != null)
            {
                var code = await _userManager.GeneratePasswordResetTokenAsync(user);
                try
                {
                    // отправитель - устанавливаем адрес и отображаемое в письме имя
                    MailAddress from = new MailAddress("illia.bezuhlyi@nure.ua", "Cargo world");
                    // кому отправляем
                    MailAddress to = new MailAddress(email);

                    // создаем объект сообщения
                    MailMessage m = new MailMessage(from, to);
                    // тема письма
                    m.Subject = "Welcome";
                    // текст письма
                    m.Body = "The password was succesfully changed";
                    // письмо представляет код html
                    m.IsBodyHtml = true;
                    // адрес smtp-сервера и порт, с которого будем отправлять письмо
                    SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);

                    // логин и пароль
                    smtp.Credentials = new NetworkCredential("illia.bezuhlyi@nure.ua", "TLnK5nd3");
                    smtp.EnableSsl = true;
                    smtp.Send(m);

                    var res = await _userManager.ResetPasswordAsync(user, code, pass);


                }
                catch (Exception ex)
                {

                }
            }
        }

    }
}

CargoWorld/Controllers/CarController.cs
using CargoWorld.Data;
using CargoWorld.Data.FileManager;
using CargoWorld.Data.Repositories;
using CargoWorld.Models;
using CargoWorld.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CargoWorld.Controllers
{
    [Authorize]
    public class CarController : Controller
    {
        private CarRepository _carRepository;
        private UserManager<ApplicationUser> _userManager;
        private IFileManager _fileManager;

        public CarController(IRepository<Car> carRepository, 
            UserManager<ApplicationUser> userManager,
            IFileManager fileManager)
        {
            _carRepository = (CarRepository)carRepository;
            _userManager = userManager;
            _fileManager = fileManager;
        }

        [HttpGet]
        public async Task<IActionResult> CreateCarAsync(int? id)
        {
            if (id == null)
                return View(new CarViewModel());
            else
            {
                var car = _carRepository.Get((int)id);
                return View(new CarViewModel
                {
                    IdOwner = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)),
                    IdCar = (int)car.IdCar,
                    IdDriver = car.IdDriver,
                    IdGroup = null,
                    CarModel = car.CarModel,
                    CarcassNumber = car.CarcassNumber,
                    RegistrationNumber = car.RegistrationNumber,
                    Photo = car.Photo,
                    Color = car.Color,
                    CargoType = car.CargoType,
                    CarType = car.CarType,
                    CarryingCapacity = car.CarryingCapacity,
                    CarryingCapacitySqM = car.CarryingCapacitySqM,
                    HeightCargoCompartment = car.HeightCargoCompartment,
                    WidthCargoCompartment = car.WidthCargoCompartment,
                    LengthCargoCompartment = car.LengthCargoCompartment,
                    CostPerKm = car.CostPerKm
                });
            }
        }

        [HttpPost]
        public async Task<IActionResult> CreateCar(CarViewModel cvm)
        {
            if (!ModelState.IsValid)
            {
                return View(cvm);
            }
            var car = new Car
            {
                IdOwner = await _userManager.FindByIdAsync(_userManager.GetUserId(HttpContext.User)),
                IdCar = cvm.IdCar,
                IdDriver = String.Empty,
                IdGroup = cvm.IdGroup,
                CarModel = cvm.CarModel,
                CarcassNumber = cvm.CarcassNumber,
                RegistrationNumber = cvm.RegistrationNumber,
                Photo = await _fileManager.SaveImage(cvm.Image),
                Color = cvm.Color,
                CargoType = cvm.CargoType,
                CarType = cvm.CarType,
                CarryingCapacity = cvm.CarryingCapacity,
                CarryingCapacitySqM = cvm.CarryingCapacitySqM,
                HeightCargoCompartment = cvm.HeightCargoCompartment,
                WidthCargoCompartment = cvm.WidthCargoCompartment,
                LengthCargoCompartment = cvm.LengthCargoCompartment,
                CostPerKm = cvm.CostPerKm
            };


            if (cvm.IdCar > 0)
                _carRepository.Update(car);
            else
                _carRepository.Create(car);

            if (await _carRepository.SaveChangesAsync())
                return RedirectToAction("Index", "Home");
            else
                return View(car);
        }


        public IActionResult ACar(int id)
        {
            return View(_carRepository.Get(id));
        }


        [HttpGet]
        public IActionResult ImDriving()
        {
            var res = _carRepository.IAmDriving(_userManager.GetUserId(HttpContext.User));
            return View(res);
        }

        public async Task<IActionResult> DrivingRefuseAsync(int idCar)
        {
            await _carRepository.RefuseDrivingAsync(idCar);
            // refusing
            return RedirectToAction("ImDriving");
        }


        [HttpGet]
        public IActionResult MyCars(int pageNumber)
        {
            if (pageNumber < 1)
                return RedirectToAction("MyCars", new { pageNumber = 1 });

            var list = _carRepository.GetAll(_userManager.GetUserId(HttpContext.User), pageNumber);
            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Remove(int id)
        {
            _carRepository.Remove(id);
            await _carRepository.SaveChangesAsync();
            return RedirectToAction("Index", "Home");
        }

        [HttpGet("/Image/{image}")]
        public IActionResult Image(string image)
        {
            var type = image.Substring(image.LastIndexOf('.')+1);
            return new FileStreamResult(_fileManager.ImageStream(image), $"image/{type}");
        }
    }
}

CargoWorld/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href=" https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css " rel="stylesheet " />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link href="~/css/site.css" rel="stylesheet" />

</head>


<body>
    <header>
        <div class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom  mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    Cargo world
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        @if (User.Identity.IsAuthenticated)
                        {

                            <li class="nav-item mt-3">
                                <div class="dropdown show">
                                    <a class="btn btn-secondary dropdown-toggle" style="background-color : transparent" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["cars"]
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Car" asp-action="CreateCar">@Localizer["createCar"]</a>
                                        <a class="dropdown-item" asp-controller="Car" asp-action="ImDriving">@Localizer["imDriving"]</a>
                                        <a class="dropdown-item" asp-controller="Car" asp-action="MyCars">@Localizer["myCars"]</a>
                                    </div>
                                </div>
                            </li>


                            <li class="nav-item ml-1 mt-3">
                                <div class="dropdown show">
                                    <a class="btn btn-secondary dropdown-toggle" style="background-color : transparent" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["groups"]
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Groups" asp-action="CreateGroup">
                                            @Localizer["createGroup"]

                                        </a>
                                        <a class="dropdown-item" asp-controller="Groups" asp-action="GroupList">
                                            @Localizer["myGroups"]

                                        </a>
                                    </div>
                                </div>
                            </li>


                            <li class="nav-item ml-1 mt-3">
                                <div class="dropdown show">
                                    <a class="btn btn-secondary dropdown-toggle" style="background-color : transparent" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["cargos"]
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Cargo" asp-action="CreateCargo">
                                            @Localizer["createCargo"]
                                        </a>
                                        <a class="dropdown-item" asp-controller="Cargo" asp-action="CargoList">
                                            @Localizer["cargoList"]
                                        </a>
                                        <a class="dropdown-item" asp-controller="Cargo" asp-action="IMTransporting">
                                            @Localizer["cargosIm"]
                                        </a>
                                    </div>
                                </div>
                            </li>
                            <li class="nav-item ml-1 mt-3">
                                <div class="dropdown show">
                                    <a class="btn btn-secondary dropdown-toggle" style="background-color : transparent" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["requests"]
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Request" asp-action="DrivingRequest">
                                            @Localizer["drivingRequest"]
                                        </a>
                                        <a class="dropdown-item" asp-controller="Request" asp-action="CompanyToUser">
                                            @Localizer["companyToUser"]
                                        </a>
                                        <a class="dropdown-item" asp-controller="Request" asp-action="UserToCompany">
                                            @Localizer["userToCompany"]
                                        </a>
                                    </div>
                                </div>
                            </li>



                            <li class="nav-item ml-1 mt-3">
                                <form asp-controller="Home" asp-action="Search" method="get" enctype="multipart/form-data">
                                    <input class="form-control mr-sm-2" type="text" name="search" placeholder=" @Localizer["searchReq"]" />
                                </form>
                            </li>

                            <li class="nav-item ml-1 mt-3">
                                <div class="dropdown show">
                                    <a class="btn btn-secondary dropdown-toggle" style="background-color : transparent" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        @Localizer["settings"]
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                       
                                        <a class="dropdown-item" asp-controller="Auth" asp-action="ChangePass">
                                            @Localizer["change"]
                                        </a>
                                        @if (User.IsInRole("Admin"))
                                        {
                                            <a class="dropdown-item" asp-controller="Home" asp-action="AdminPanel" >@Localizer["admin"]</a>
                                        }
                                        <a class="dropdown-item" asp-controller="Auth" asp-action="Logout">
                                            @Localizer["logOut"]
                                        </a>
                                    </div>
                                </div>

                            </li>



                        }
                        else
                        {

                            <li class="nav-item mt-3 mb-3 mr-2">
                                <a class="btn btn-dark" asp-controller="Auth" asp-action="Login">@Localizer["logIn"]</a>
                            </li>
                        }

                            <li class="nav-item ml-3 mb-4 pt-2">
                                <div>
                                    @await Html.PartialAsync("_SelectLanguagePartial.cshtml")
                                </div>
                            </li>

                    </ul>
                </div>
            </div>
        </div>

    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <footer class="d-inline-flex ml-auto container fixed-bottom">
        <p class="float-right">@Localizer["ownrRights"]</p>
        <p class="float-right">@Localizer["made"] </p>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CargoWorld/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures
.Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
.ToList();
}

<form asp-controller="Home" asp-action="SetLanguage" style="margin-top:20px;"
            asp-route-returnUrl="@Context.Request.Path"
            method="post" class="form-horizontal">
     <select name="culture" onchange="this.form.submit();"
                                                                        asp-for="@requestCulture.RequestCulture.UICulture.Name"
                                                                        asp-items="cultureItems"></select>
</form>